  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'ci/images/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/wss-bridge:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wss-bridge:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'wss-bridge'
    - '--image'
    - 'gcr.io/$PROJECT_ID/wss-bridge:$COMMIT_SHA'
    - '--region'
    - 'europe-west1-b'
  images:
  - 'gcr.io/$PROJECT_ID/wss-bridge:$COMMIT_SHA'
  options:
    logging: CLOUD_LOGGING_ONLY